// ! Do not edit this file directly, use npm run router instead
import { Outlet, Route, Routes } from 'react-router-dom'

import ProductLayout from '~app/product.../layout'
import Product from '~app/product.../page'

import NotFound from '~components/common/NotFound'

function ProductSubRouter() {
  return (
    <Routes>
      <Route
        path=""
        element={<ProductLayout><Outlet /></ProductLayout>}
      >
        <Route
          index
          element={<Product />}
        />
        <Route
          path="*"
          element={<NotFound />}
        />
      </Route>
    </Routes>
  )
}

export default ProductSubRouter
