// ! Do not edit this file directly, use npm run router instead
import { Suspense, lazy } from 'react'
import { BrowserRouter, Outlet, Route, Routes } from 'react-router-dom'

import AppLayout from '~app/layout'
import App from '~app/page'
import PricingLoading from '~app/pricing.../loading'
import ProductLoading from '~app/product.../loading'
import LegalLoading from '~app/legal.../loading'

import CenteredSpinner from '~components/common/CenteredSpinner'
import NotFound from '~components/common/NotFound'

const PricingSubRouter = lazy(() => import('~router/subRouters/PricingSubRouter'))
const AuthenticationSubRouter = lazy(() => import('~router/subRouters/AuthenticationSubRouter'))
const ProductSubRouter = lazy(() => import('~router/subRouters/ProductSubRouter'))
const LegalSubRouter = lazy(() => import('~router/subRouters/LegalSubRouter'))

function Router() {
  return (
    <BrowserRouter>
      <Suspense fallback={<CenteredSpinner />}>
        <Routes>
          <Route
            path="/"
            element={<AppLayout><Outlet /></AppLayout>}
          >
            <Route
              index
              element={<App />}
            />
            <Route
              path="pricing/*"
              element={<Suspense fallback={<PricingLoading />}><PricingSubRouter /></Suspense>}
            />
            <Route
              path="authentication/*"
              element={<Suspense fallback={<CenteredSpinner />}><AuthenticationSubRouter /></Suspense>}
            />
            <Route
              path="product/*"
              element={<Suspense fallback={<ProductLoading />}><ProductSubRouter /></Suspense>}
            />
            <Route
              path="legal/*"
              element={<Suspense fallback={<LegalLoading />}><LegalSubRouter /></Suspense>}
            />
            <Route
              path="*"
              element={<NotFound />}
            />
          </Route>
        </Routes>
      </Suspense>
    </BrowserRouter>
  )
}

export default Router
